
export const MOCK_USERS = [
  { 
    employeeId: '509034',
    username: '509034', 
    password: 'PEA509034', 
    name: 'นายพัฒนศักดิ์ เกิดอู่ม', 
    role: 'ADMIN',
    position: 'พนักงานบันทึกข้อมูลคอมพิวเตอร์',
    email: 'pattanasak.ker@pea.co.th',
    phone: '080-4357084',
    peaOffice: 'การไฟฟ้าส่วนภูมิภาค เขต 3 (ภาคกลาง) จังหวัดนครปฐม',
    department: 'กองปฏิบัติการ',
    region: 'นครปฐม',
    status: 'ACTIVE'
  },
  { 
    employeeId: '512370',
    username: '512370', 
    password: 'PEA512370', 
    name: 'นายวัชรพงษ์ อินขลิบ', 
    role: 'INSPECTOR',
    position: 'วิศวกรไฟฟ้า',
    email: 'watcharapong.ink@pea.co.th',
    phone: '-',
    peaOffice: 'การไฟฟ้าส่วนภูมิภาค เขต 3 (ภาคกลาง) จังหวัดนครปฐม',
    department: 'กองปฏิบัติการ',
    region: 'นครปฐม',
    status: 'ACTIVE'
  },
  { 
    employeeId: '498232',
    username: '498232', 
    password: 'PEA498232', 
    name: 'นายชูฤทธิ์ ปานสกุล', 
    role: 'MANAGER',
    position: 'ผู้ช่วยหัวหน้าแผนก',
    email: 'churit.pan@pea.co.th',
    phone: '087 - 4515695',
    peaOffice: 'การไฟฟ้าส่วนภูมิภาค เขต 3 (ภาคกลาง) จังหวัดนครปฐม',
    department: 'กองปฏิบัติการ',
    region: 'นครปฐม',
    status: 'ACTIVE'
  },
  { 
    employeeId: '556820',
    username: '556820', 
    password: 'SPP556820', 
    name: 'นางสาวภัทรพรรณ นุชจ้อย', 
    role: 'VENDER',
    position: 'ผู้ช่วยวิศวกรโครงการ',
    email: 'pattaraphan.nut@interpower.co.th',
    phone: '087 - 4515695',
    peaOffice: 'Interpower Plant Co., Ltd.',
    department: 'โครงการ NPT3 Solar Farming',
    region: 'นครปฐม',
    status: 'ACTIVE'
  },
  { 
    employeeId: '520111',
    username: '520111', 
    password: 'PEA520111', 
    name: 'นายสมชาย สายลม', 
    role: 'INSPECTOR',
    position: 'ช่างสายอากาศ',
    email: 'somchai.sai@pea.co.th',
    phone: '081-222-3333',
    peaOffice: 'การไฟฟ้าส่วนภูมิภาค เขต 3 (ภาคกลาง) จังหวัดนครปฐม',
    department: 'กองบำรุงรักษาระบบจำหน่าย',
    region: 'นครปฐม',
    status: 'ACTIVE'
  },
  { 
    employeeId: '485920',
    username: '485920', 
    password: 'PEA485920', 
    name: 'นางกัลยา มุ่งมั่น', 
    role: 'MANAGER',
    position: 'หัวหน้ากองปฏิบัติการ',
    email: 'kanlaya.mung@pea.co.th',
    phone: '089-111-2222',
    peaOffice: 'การไฟฟ้าส่วนภูมิภาค เขต 3 (ภาคกลาง) จังหวัดนครปฐม',
    department: 'กองปฏิบัติการ',
    region: 'นครปฐม',
    status: 'ACTIVE'
  },
  { 
    employeeId: '518293',
    username: '518293', 
    password: 'PEA518293', 
    name: 'นายวิชัย กล้าหาญ', 
    role: 'INSPECTOR',
    position: 'วิศวกรไฟฟ้าส่วนสถานี',
    email: 'vichai.kla@pea.co.th',
    phone: '085-555-6666',
    peaOffice: 'การไฟฟ้าส่วนภูมิภาค เขต 3 (ภาคกลาง) จังหวัดนครปฐม',
    department: 'กองบำรุงรักษาสถานีไฟฟ้า',
    region: 'นครปฐม',
    status: 'ACTIVE'
  },
  { 
    employeeId: 'V9001',
    username: 'V9001', 
    password: 'V9001PASS', 
    name: 'สมเกียรติ พลังงานสะอาด', 
    role: 'VENDER',
    position: 'วิศวกรควบคุมระบบ',
    email: 'somkiat@solartech.co.th',
    phone: '090-999-8888',
    peaOffice: 'SolarTech Solution Co., Ltd.',
    department: 'ฝ่ายบำรุงรักษาโรงไฟฟ้า',
    region: 'นครปฐม',
    status: 'ACTIVE'
  }
];
